import { RouterUtils } from '../../utils/common/RouterUtils';
import { LHCommonTitleBar, LHCommonTitleBarLeftNavBack } from '../../views/common/LHCommonTitleBar';
import { LHWebView } from '../../views/common/LHWebView';
import { webview } from '@kit.ArkWeb';
import { LHAppSettingsTextSizePlanModel } from '../../models/common/LHAppSettingsTextSizePlanModel';
import { LHAppSettingsTextSizePlans } from '../../models/common/LHAppSettingsTextSizePlans';
import {
  GlobalAppSettings,
  GLOBAL_APP_SETTINGS_EVENT_TYPE,
  GLOBAL_APP_SETTINGS_KEY_TEXT_SIZE_PLAN
} from '../../utils/common/GlobalAppSettings';
import { emitter } from '@kit.BasicServicesKit';
import { GLOBAL_APP_SETTINGS_CHANGED_EVENT } from '../../utils/common/GlobalAppSettings';
import { getScreenBottomSafeZoneHeightPx, getScreenTopSafeZoneHeightPx } from '../../utils/common/ScreenUIAdapter';
import { ScreenObserver, ScreenStatusInfo } from '../../utils/common/uiobserver/ScreenObserver';
import window from '@ohos.window';
import inspector from '@ohos.arkui.inspector';
import { openCustomDialog } from '../../utils/common/DialogUtils';
import { TakePhotoDialog } from '../../views/TakePhotoDialog';
import { ClassroomArticle } from '../../views/ClassroomArticle';
import { res2string } from '../../utils/common/Utils';
import { LocalTTSService } from '../../utils/LocalTTSService';

export namespace Classroom {
  export function go(params: Record<string, ResourceStr | undefined>) {
    RouterUtils.navPushPath('Classroom', params);
  }
}

@Builder
export function ClassroomBuilder() {
  ClassroomComponent()
}

/** 传递的url参数。 */
export const LESSON_INFO: string = 'url_params';

/** 课程名称。 */
export const LESSON_NAME: string = 'lesson_name';

/** 文章内容。 */
export const ARTICLE_CONTENT: string = 'article_content';

/** 屏幕中WebView组件的ID。 */
const CLASSROOM_VIEWER_ID: string = 'classroom_viewer';

/**
 * 网页浏览器，基于原生Web组件实现。
 * @author li.hao85
 */
@Component
struct ClassroomComponent {

  /** 应用文字字号方案。 */
  @State appTextSizePlan: LHAppSettingsTextSizePlanModel = LHAppSettingsTextSizePlans.SMALL;

  /** 地址信息。 */
  private url?: ResourceStr;

  /** 课程名称。 */
  private lessonName?: ResourceStr;

  /** 文章内容。 */
  private articleContent?: ResourceStr;

  /** 浏览器控制器。 */
  private controller?: webview.WebviewController;

  /** 顶部安全区高度。 */
  @State topSafeZoneHeightVp: number = px2vp(getScreenTopSafeZoneHeightPx());

  /** 底部安全区高度。 */
  @State bottomSafeZoneHeightVp: number = px2vp(getScreenBottomSafeZoneHeightPx());

  /** 标题栏可见性。 */
  @State titleVisible: boolean = true;

  /** WebView组件绘制完成监听。 */
  @State private drawComplete: boolean = false;

  /** 文章是否可见。 */
  @State private articleVisible: boolean = false;

  /** WebView组件绘制进度监听。 */
  private drawListener?: inspector.ComponentObserver;

  private onGlobalAppSettingsChangedEvent: Callback<emitter.EventData> = (dataWrap: emitter.EventData) => {
    if (dataWrap.data) {
      let eventType: string = dataWrap.data[GLOBAL_APP_SETTINGS_EVENT_TYPE] as string;
      switch (eventType) {
        case GLOBAL_APP_SETTINGS_KEY_TEXT_SIZE_PLAN:
          this.appTextSizePlan = GlobalAppSettings.textSizePlan();
          break;
        default:
          break;
      }
    }
  };

  private onDrawCompleteCallback: Callback<void> = () => {
    this.drawComplete = true;
  };

  build() {
    NavDestination() {
      RelativeContainer() {
        LHWebView({
          src: this.url,
          mobileMode: true,
          onControllerAttachedCallback: (webViewController: webview.WebviewController): void => this.onControllerAttachedCallback(webViewController)
        })
          .id(CLASSROOM_VIEWER_ID)
          .width('100%')
          .height('100%')
          .onClick((_: ClickEvent) => {
            this.titleVisible = !this.titleVisible;
          })
        Column() {
          LHCommonTitleBar({
            centerTitleText: this.lessonName ?? $r('app.string.browser'),
            centerTitleTextSize: this.appTextSizePlan.unifiedTitleCenterTextSize,
            leftAction: LHCommonTitleBarLeftNavBack,
            rightAction: (): void => this.TakePhoto(),
            titleBarBg: Color.Transparent
          })
        }
        .padding({ top: this.topSafeZoneHeightVp })
        .backgroundColor(Color.White)
        .visibility(this.titleVisible ? Visibility.Visible : Visibility.None)
        .alignRules({
          top: { anchor: '__container__', align: VerticalAlign.Top }
        })
        if (this.articleContent) {
          ClassroomArticle({
            appTextSizePlan: this.appTextSizePlan,
            articleContent: res2string(this.articleContent)
          })
            .visibility(this.articleVisible ? Visibility.Visible : Visibility.None)
            .margin({
              bottom: Math.max(this.bottomSafeZoneHeightVp, 16),
              left: 16,
              right: 16
            })
            .alignRules({
              bottom: { anchor: '__container__', align: VerticalAlign.Bottom },
              start: { anchor: '__container__', align: HorizontalAlign.Start },
              end: { anchor: '__container__', align: HorizontalAlign.End }
            })
        }
        Button() {
          Image($r('app.media.ic_book'))
            .objectFit(ImageFit.Contain)
            .width(30)
            .height(30)
        }
        .width(50)
        .height(50)
        .borderRadius(25)
        .borderWidth(2)
        .borderColor($r('app.color.main_selected_color'))
        .backgroundColor(Color.White)
        .margin({
          bottom: Math.max(this.bottomSafeZoneHeightVp, 16),
          right: 16
        })
        .opacity(0.8)
        .alignRules({
          bottom: { anchor: '__container__', align: VerticalAlign.Bottom },
          end: { anchor: '__container__', align: HorizontalAlign.End }
        })
        .onClick(() => {
          if (this.articleContent) {
            this.articleVisible = !this.articleVisible;
            LocalTTSService.getInstance().stop();
            if (this.articleVisible) {
              setTimeout(() => {
                if (this.articleContent) {
                  LocalTTSService.getInstance().speak(res2string(this.articleContent));
                }
              }, 0);
            }
          }
        })
      }
      .width('100%')
      .height('100%')
      .backgroundColor($r('app.color.main_bg_gray_color'))
    }
    .hideTitleBar(true)
    .backButtonIcon(undefined)
    .onReady((context: NavDestinationContext) => {
      let urlParams: Record<string, ResourceStr | undefined> =
        RouterUtils.navGetParams(context) as Record<string, ResourceStr | undefined>;
      this.url = urlParams[LESSON_INFO];
      this.lessonName = urlParams[LESSON_NAME];
      this.articleContent = urlParams[ARTICLE_CONTENT];
      this.appTextSizePlan = GlobalAppSettings.textSizePlan();
      emitter.on(GLOBAL_APP_SETTINGS_CHANGED_EVENT, this.onGlobalAppSettingsChangedEvent);
      ScreenObserver.subscribe(this.getUIContext(), (screenStatus: ScreenStatusInfo) => {
        if (screenStatus.avoidArea !== undefined) {
          if (screenStatus.avoidAreaType === window.AvoidAreaType.TYPE_SYSTEM) {
            this.topSafeZoneHeightVp = px2vp(screenStatus.avoidArea.topRect.height);
          } else if (screenStatus.avoidAreaType === window.AvoidAreaType.TYPE_NAVIGATION_INDICATOR) {
            this.bottomSafeZoneHeightVp = px2vp(screenStatus.avoidArea.bottomRect.height);
          }
        }
      });
      this.drawListener = this.getUIContext().getUIInspector().createComponentObserver(CLASSROOM_VIEWER_ID);
      this.drawListener.on('draw', this.onDrawCompleteCallback);
    })
    .onBackPressed(() => {
      try {
        if (this.controller !== undefined && this.controller.accessBackward()) {
          this.controller.backward();
          return true;
        }
      } catch (error) {
      }
      return false;
    })
    .onDisAppear(() => {
      emitter.off(GLOBAL_APP_SETTINGS_CHANGED_EVENT, this.onGlobalAppSettingsChangedEvent);
      ScreenObserver.unsubscribe(this.getUIContext());
      this.drawListener?.off('draw', this.onDrawCompleteCallback);
      LocalTTSService.getInstance().stop();
    })
  }

  /** 截屏保存。 */
  @Builder
  private TakePhoto() {
    if (this.drawComplete) {
      Image($r('app.media.ic_take_photo_green'))
        .width(48)
        .height(48)
        .padding(12)
        .objectFit(ImageFit.Contain)
        .onClick((_: ClickEvent) => this.takePhoto())
    }
  }

  /**
   * 控制器绑定完毕回调。
   * @param webViewController WebView控制器。
   */
  private onControllerAttachedCallback(webViewController: webview.WebviewController) {
    this.controller = webViewController;
  }

  /** 拍照保存。 */
  private takePhoto() {
    this.getUIContext().getComponentSnapshot().get(CLASSROOM_VIEWER_ID)
      .then((img: PixelMap) => {
        openCustomDialog({
          builder: wrapBuilder(TakePhotoDialogBuilder),
          data: [img],
        });
      })
      .catch(() => {});
  }
}

@Builder
function TakePhotoDialogBuilder(params: object, closeCallback: Callback<void, void>) {
  TakePhotoDialog({
    img: (params as Array<object>)[0] as ESObject as PixelMap,
    closeCallback: closeCallback
  })
}